name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker Compose Plugin
        run: sudo apt-get install docker-compose-plugin
      - name: Log in to Docker hub
        run: echo "${{secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Create Docker image
        run: docker compose build
      - name: Push to Docker Hub
        run: docker push "${{secrets.DOCKER_USERNAME}}"/react_app_demo:latest
